// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Safe localStorage access (SSR compatibility)
const getStorage = (): Storage | null => {
  if (typeof window === 'undefined') return null;
  try {
    return localStorage;
  } catch (e) {
    return null;
  }
};

// Validate environment variables
const isValidConfig = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_URL.startsWith('http') && 
  SUPABASE_PUBLISHABLE_KEY.length > 0;

if (!isValidConfig) {
  const errorMsg = '⚠️ Supabase configuration is invalid or missing. Check your environment variables.';
  if (import.meta.env.DEV) {
    console.error(errorMsg);
    console.error('Required: VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY');
    console.error(`Current URL: ${SUPABASE_URL || 'MISSING'}`);
    console.error(`Current Key: ${SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...` : 'MISSING'}`);
  } else {
    console.error(errorMsg);
  }
}

// Additional validation - check if key looks valid (JWT format)
if (SUPABASE_PUBLISHABLE_KEY && !SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')) {
  console.warn('⚠️ API key does not appear to be in JWT format. Please verify your VITE_SUPABASE_PUBLISHABLE_KEY.');
}

// Use placeholder values if missing to prevent crashes
const safeUrl = SUPABASE_URL || 'https://placeholder.supabase.co';
const safeKey = SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDUxOTIwMDAsImV4cCI6MTk2MDc2ODAwMH0.placeholder';

export const supabase = createClient<Database>(safeUrl, safeKey, {
  auth: {
    storage: getStorage(),
    persistSession: typeof window !== 'undefined',
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'x-client-info': 'quezon-bukidnon-website',
    },
  },
  db: {
    schema: 'public',
  },
});

// Export validation helper
export const isSupabaseConfigured = isValidConfig;